### ISSUE TITLE
Image becomes unresponsive after zooming-in / escaping rapidly a few times.

### ISSUE THREAD

**Issue by guillaumelachaud** [rpearce/react-medium-image-zoom#393] opened 2023-01-16 18:32 UTC
## Issue Type

- [X] Bug report
- [ ] Feature request
- [ ] Question / support request
- [ ] Other

## Description
https://user-images.githubusercontent.com/2076017/212744982-e2466b3c-96f7-46f5-b14c-7bd140aa8ad5.mp4

This one looks a bit like a race condition somewhere and can take quite some time to reproduce.
It happens when zooming-in by click and then zooming out with the escape key. And you do that quickly multiple times until at some point the image becomes unresponsive. It also becomes impossible to click on the text anymore. Double clicking anywhere ends up selecting the image, so it looks like the overlay might still have the focus somehow.

Tested locally on `5.1.2` and can also reproduce on the Storybook samples

**Comment by rpearce** [comment] 2023-01-17 00:09
This looks like a fun one! Thank you for the report.

**Comment by rpearce** [comment] 2023-08-24 15:34
@tommoor Are you saying the issue went away but came back recently with the ESC changes?

And do you have bug reproduction steps like above, or are they slightly different?

Thanks for your time!

**Comment by tommoor** [comment] 2023-08-24 15:45
Just confirming that it still exists and wasn't incidentally fixed by those changes.

I can reproduce usually in a few seconds with the steps above, just click and hit ESC rapidly.

**Comment by rpearce** [comment] 2024-05-13 09:29
After sitting here for 5min and trying to recreate this in Chrome tonight, I can't break it by clicking a bunch nor clicking with ESC a bunch. If some new info comes to light on how I can repro this, I'll reopen.

**Closed by rpearce** 2024-05-13 09:29 UTC
Labels: bug
