### ISSUE TITLE
Zoomable image breaks on Chrome

### ISSUE THREAD

**Issue by brew-matija** [rpearce/react-medium-image-zoom#470] opened 2024-03-15 09:16 UTC
## Issue Type

- [x] Bug report
- [ ] Feature request
- [ ] Question / support request
- [ ] Other

## Description
This bug is apparent only in Chrome. Tested it in Firefox and Safari, those work as normal. When clicking a zoomable image, it sometimes works properly, and other times it doesn't show a magnifying glass cursor, just a regular pointer and if you click the image then it disappears and the other page interactions are broken. Escape key does nothing and the only way out is to refresh the page. On subsequent refreshes the component sometimes works properly and sometimes doesn't.
Tried both the Controlled and Uncontrolled versions, same thing.

Place detailed information here
Chrome Version 122.0.6261.129 (Official Build) (arm64)
MacOS Sonoma Version 14.0 (23A344)
Next 13.5.6

**Comment by rpearce** [comment] 2024-03-15 13:25
@brew-matija Can you please provide a functioning sample of this breaking for me to work with? It works for me in Chrome. Thank you for providing browser, OS, and environment details.

**Comment by jiayihu** [comment] 2024-05-12 20:32
I've noticed the same issue and it can be reproduced with a lazy-loaded image, by clicking the image before the image has been loaded.

**Comment by rpearce** [comment] 2024-05-12 21:30
Ah, that's interesting. Thanks for the context!

**Comment by rpearce** [comment] 2024-05-13 02:30
I've got a fix for this I'll try to get out in the next 6-10 hours

**Closed** 2024-05-13 08:51 UTC
Labels: bug

**Comment by rpearce** [comment] 2024-05-13 09:00
@brew-matija @jiayihu This should be fixed in `react-medium-image-zoom@5.2.1`. If there are additional issues, you know where to find me! I added you both to the "All Contributors" list in the README; thank you for your bug reporting.

**Comment by rpearce** [comment] 2024-05-13 09:24
Update: I found an accidental dependency on `@storybook/test` that shouldn't there and just released `react-medium-image-zoom@5.2.2`. It won't make a difference for this issue, but it is the latest, and it should reduce the dependencies size back down to zero.

**Comment by jiayihu** [comment] 2024-05-15 19:58
I finally tested the fix and I can confirm it's working correctly now, thanks for the quick fix ❤️
