### ISSUE TITLE
Image disappeared on click to Zoom

### ISSUE THREAD

**Issue by holybank** [rpearce/react-medium-image-zoom#424] opened 2023-05-28 04:40 UTC
## Issue Type

- [x ] Bug report

## Description

There are many images in the website (300+ images) and all are lazy loaded.
Once the page is loaded, some random number of images at the end of the image list are disappeared upon click to Zoom.
I inspected the element and see that it has _data-rmiz-content="not-found"_ on it even though the src of the image points to the correct path and it even shows the image in developer tool when I hover the link.
I use default basic usage of the component `<Zoom><MyImage . . . /></Zoom>`

![image](https://github.com/rpearce/react-medium-image-zoom/assets/60592334/7d20b7e1-4149-4fee-a0e8-7b186e90faa5)

## Expected Output

It should display the image and zoom correctly when the src path is correct without disappearing and not even trigger the zoom.

**Comment by rpearce** [comment] 2023-05-30 13:20
Hi! I'll look at this when I get some time. Thanks for reporting it.

**Comment by rpearce** [comment] 2023-06-24 10:42
@holybank If you're able to put together an example of what you're experiencing, that will enable me to diagnose and fix this a lot faster!

**Comment by rpearce** [comment] 2023-11-12 14:36
I'm not able to reproduce this, and without an example, I'm going to close this for now. If this is still an issue, and an example is provided, I can reopen this and give it another shot.

**Closed by rpearce** 2023-11-12 14:36 UTC
