### ISSUE TITLE
Zooming effect breaks when images is clicked while scrolling

### ISSUE THREAD

**Issue by Binibeno** [rpearce/react-medium-image-zoom#439] opened 2023-08-17 21:16 UTC
## Issue Type

- [x] Bug report
- [ ] Feature request
- [ ] Question / support request
- [ ] Other

## Description

As per the title says, the zooming effect becomes broken if the pages is being scrolled when the images is clicked. It sometimes takes a few tries to get but when the images does get stuck, the page becomes unusable, because this component blocks the scrolling and interaction with any other part of the page. The close icon does appear on the top right side of the page but it is not clickable.

There is no special config needed to reproduce this issue, it works on every storybook demo, where there is space to scroll.

For example this one: https://rpearce.github.io/react-medium-image-zoom/?path=/story/galleries--image-gallery

I've tried hacking around this issue by disabling scroll (setting the html body's overflow to hidden) when the image is clicked, but it did not work.

(I'm using Chrome 115 and Windows if that matters)

If anyone has any hacks or possible fixes for this please let me know! Maybe anyone has any alternative packages I can switch to, that function similarly to this one? 
Any help would be appreciated!

**Comment by rpearce** [comment] 2023-08-18 02:56
@Binibeno I can't reproduce this on macOS after trying for a few minutes (Chrome, Firefox, Safari), so it might be confined to Windows. If that's the case, I'll need to reproduce it there and use that for testing any fixes that need to be made.

Code contributions to the project are also welcome! If you are interested in that, see the [contributing guide](https://github.com/rpearce/react-medium-image-zoom/blob/main/CONTRIBUTING.md) for more information.

If you're able to make a screen recording of the issue, that would be _very_ helpful! If not, that's ok, too.

**Comment by Binibeno** [comment] 2023-08-18 20:44
I created a screen recording, I've attached it with this reply. Hope this helps!

It only seems to happen when I'm using a mouse, not on touchpad or touchscreen.

https://github.com/rpearce/react-medium-image-zoom/assets/53515381/50fba14d-1e6f-4233-b4fe-257f1a39d7d6

**Comment by rpearce** [comment] 2023-08-19 04:15
@Binibeno This is great! Thank you for taking the time to make the video.

**Comment by rpearce** [comment] 2024-06-06 03:52
Yep, I just ran into this issue with my Logitech mouse. Will fix up

**Comment by tommoor** [comment] 2024-06-19 12:00
It feels like a lot of the bugs on this lib are unfortunately caused by the use of listening for `transitionend`, does this likely fall into that same bucket?

**Comment by rpearce** [comment] 2024-06-20 05:18
@tommoor I haven't tallied all the sources of bugs, but that doesn't feel right to me to say. `transitionend` may be the culprit here, but it's very effective for timing things with transitions. The only alternative I think I could use from a timing perspective is `setTimeout`, and that's brittle for a few reasons.

I won't know until I dig in, and this is my next priority.

**Comment by rpearce** [comment] 2024-06-20 08:40
I can't use a mouse until tomorrow or the next day, but looking at the logic, the first thing I'm going to look at is the use of the `wheel` listener _before_ the image has zoomed. This currently makes it so you can click and then mouse-wheel to close it before it opens, but if the wheel is already going while you click on it, something may be getting stuck. We'll see...

https://github.com/rpearce/react-medium-image-zoom/blob/8040ab28728335fff7f91beb65fdcf992896dcc7/source/Controlled.tsx#L622

**Closed** 2024-06-22 02:54 UTC
Labels: bug

**Comment by rpearce** [comment] 2024-06-22 03:01
@Binibeno This should be resolved in `react-medium-image-zoom@5.2.5`. Thanks for the report, and thank you for your patience with the fix. You have been added to the README's all contributors list for your bug report. Many thanks! 💜
