### ISSUE TITLE
preventDefault for the un-zoom button

### ISSUE THREAD

**Issue by kayvaninvemo** [rpearce/react-medium-image-zoom#746] opened 2024-10-17 06:08 UTC
https://github.com/rpearce/react-medium-image-zoom/blob/4ad2a9ceebdbdf247f388c69190f07b90cfa4d71/source/Controlled.tsx#L260

here we need to preventDefault, otherwise it causes un expected behaviour if the zoom component it self is inside a dialog.

**Comment by rpearce** [comment] 2024-10-21 14:16
@kayvaninvemo do you have time to put an example into a CodeSandbox that I can test with?

**Comment by rpearce** [comment] 2024-11-03 03:08
@kayvaninvemo I unfortunately don't yet understand what the problem is. If you can help me understand it with a demo, that would be helpful.

**Comment by tjx666** [comment] 2024-11-03 05:27
@rpearce 

try here: https://stackblitz.com/edit/vitejs-vite-nddcft?file=src%2FApp.tsx

1. click button to open dialog
2. click image in dialog to open zoomed image
3. click the zoomed image
	- expect: only exit the zommed state, but keep dialog open
	- actual: not only exit the zoomed state, but also exit modal

**Comment by kayvaninvemo** [comment] 2024-11-04 14:39
@tjx666 this is exactly my issue. I did a workaround [here](https://stackblitz.com/edit/vitejs-vite-djxwwz?file=src%2FApp.tsx,src%2Fmain.tsx)

```
      onClose={(e: any) => {
        if (e.target?.id?.match(/rmiz-modal-.*/)) {
          return;
        }
        handleClose();
      }}
```

**Comment by rpearce** [comment] 2024-11-07 13:20
@tjx666 @kayvaninvemo Got it! Will fix. Many thanks for y'all's patience and sharing info.

**Comment by rpearce** [comment] 2024-11-12 03:10
Well, I thought this would be fixed in `react-medium-image-zoom@5.2.11`, but I went back to that stackblitz, updated the `package.json`, re-installed, and gave it a whirl, but no difference.

Could one of y'all give this a try for me? It's not impossible `@mui/material` is doing something unexpected.

**Comment by rpearce** [comment] 2024-12-04 11:12
@djaffer This was not the case for me when I tested with a plain dialog element. Are you also using `@mui/material`?

**Closed** 2024-12-29 18:17 UTC

**Comment by rpearce** [comment] 2024-12-29 18:19
At least for `onClose` and with MUI, this should now be resolved in `react-medium-image-zoom@5.2.13`. Thanks for your patience!

**Comment by tjx666** [comment] 2025-05-01 11:16
But not fix for shadcn/redix dialog

**Comment by rpearce** [comment] 2025-05-01 14:06
@tjx666 If something isn't working, please open a new issue (like you did here: https://github.com/rpearce/react-medium-image-zoom/issues/817) with an example reproduction (like in CodeSandbox) of the issue so that I can help sort it out when I get time.
